name: CI/CD Docker → Docker Hub → Render

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/docker-express:${{ github.sha }} .

      - name: Push Docker Image (tagged)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-express:${{ github.sha }}

      - name: Push Docker Image (latest)
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/docker-express:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/docker-express:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-express:latest

  trigger-render:
    name: Optional Trigger Render Deploy Hook
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Call Render Deploy Hook
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}